#pragma once

#include "stm32f4xx_hal.h"


#define ACTUATOR_CFG_SPEED_RATIO_EXTEND    100U
#define ACTUATOR_CFG_SPEED_RATIO_RETRACT   200U

#define ACTUATOR_PORT_MOTOR_FWD   GPIOD
#define ACTUATOR_PIN_MOTOR_FWD    GPIO_PIN_12
#define ACTUATOR_PORT_MOTOR_BWD   GPIOD
#define ACTUATOR_PIN_MOTOR_BWD    GPIO_PIN_14

#define ACTUATOR_PORT_SW1         GPIOA
#define ACTUATOR_PIN_SW1          GPIO_PIN_0
#define ACTUATOR_PORT_SW2         GPIOE
#define ACTUATOR_PIN_SW2          GPIO_PIN_4


#define ACTUATOR_GET_TICK()  HAL_GetTick()


#define ACTUATOR_READ_SW1()  (HAL_GPIO_ReadPin(ACTUATOR_PORT_SW1, ACTUATOR_PIN_SW1) == GPIO_PIN_SET)
#define ACTUATOR_READ_SW2()  (HAL_GPIO_ReadPin(ACTUATOR_PORT_SW2, ACTUATOR_PIN_SW2) == GPIO_PIN_RESET)


#define ACTUATOR_CMD_MOVE_FWD()  do { \
    HAL_GPIO_WritePin(ACTUATOR_PORT_MOTOR_BWD, ACTUATOR_PIN_MOTOR_BWD, GPIO_PIN_RESET); \
    HAL_GPIO_WritePin(ACTUATOR_PORT_MOTOR_FWD, ACTUATOR_PIN_MOTOR_FWD, GPIO_PIN_SET);   \
} while(0)

#define ACTUATOR_CMD_MOVE_BWD()  do { \
    HAL_GPIO_WritePin(ACTUATOR_PORT_MOTOR_FWD, ACTUATOR_PIN_MOTOR_FWD, GPIO_PIN_RESET); \
    HAL_GPIO_WritePin(ACTUATOR_PORT_MOTOR_BWD, ACTUATOR_PIN_MOTOR_BWD, GPIO_PIN_SET);   \
} while(0)

#define ACTUATOR_CMD_STOP()  do { \
    HAL_GPIO_WritePin(ACTUATOR_PORT_MOTOR_FWD, ACTUATOR_PIN_MOTOR_FWD, GPIO_PIN_RESET); \
    HAL_GPIO_WritePin(ACTUATOR_PORT_MOTOR_BWD, ACTUATOR_PIN_MOTOR_BWD, GPIO_PIN_RESET); \
} while(0)
