#pragma once

#include "stm32f4xx_hal.h"

/* ACTUATOR COMPILE-TIME CONFIGURATION */
#define ACTUATOR_TEST_MODE_ENABLED    (1)

#define ACTUATOR_CFG_USE_U64_MATH   (1U)
#define ACTUATOR_CFG_DIR_CHANGE_DEADTIME_MS   (100UL)

#define ACTUATOR_CFG_TIMEOUT_TO_LIMIT_A_MS     (8000U)
#define ACTUATOR_CFG_TIMEOUT_TO_LIMIT_B_MS     (8000U)
#define ACTUATOR_CFG_TIMEOUT_MOVE_TO_MID_MS    (8000U)


#define ACTUATOR_CFG_DEBOUNCE_TIME_MS     (15U)

#define ACTUATOR_CFG_SPEED_RATIO_EXTEND   100U
#define ACTUATOR_CFG_SPEED_RATIO_RETRACT  200U

#define ACTUATOR_PORT_MOTOR_FWD           GPIOD
#define ACTUATOR_PIN_MOTOR_FWD            GPIO_PIN_12
#define ACTUATOR_PORT_MOTOR_BWD           GPIOD
#define ACTUATOR_PIN_MOTOR_BWD            GPIO_PIN_14

#define ACTUATOR_PORT_LIMIT_A             GPIOA
#define ACTUATOR_PIN_LIMIT_A              GPIO_PIN_0
#define ACTUATOR_PORT_LIMIT_B             GPIOC
#define ACTUATOR_PIN_LIMIT_B              GPIO_PIN_1

#define ACTUATOR_LIMIT_A_ACTIVE_LEVEL     GPIO_PIN_SET
#define ACTUATOR_LIMIT_B_ACTIVE_LEVEL     GPIO_PIN_RESET

#define ACTUATOR_GET_TICK()  			  HAL_GetTick()


/* ABSTRACTION MACROS*/
#define READ_ACTUATOR_LIMIT_A_IS_ACTIVE()  (HAL_GPIO_ReadPin(ACTUATOR_PORT_LIMIT_A, ACTUATOR_PIN_LIMIT_A) == ACTUATOR_LIMIT_A_ACTIVE_LEVEL)
/* PC1 external switch active-low wired with pull-up */
#define READ_ACTUATOR_LIMIT_B_IS_ACTIVE()  (HAL_GPIO_ReadPin(ACTUATOR_PORT_LIMIT_B, ACTUATOR_PIN_LIMIT_B) == ACTUATOR_LIMIT_B_ACTIVE_LEVEL)

#define ACTUATOR_CMD_MOVE_FWD()  do { \
    HAL_GPIO_WritePin(ACTUATOR_PORT_MOTOR_BWD, ACTUATOR_PIN_MOTOR_BWD, GPIO_PIN_RESET); \
    HAL_GPIO_WritePin(ACTUATOR_PORT_MOTOR_FWD, ACTUATOR_PIN_MOTOR_FWD, GPIO_PIN_SET);   \
} while(0)

#define ACTUATOR_CMD_MOVE_BWD()  do { \
    HAL_GPIO_WritePin(ACTUATOR_PORT_MOTOR_FWD, ACTUATOR_PIN_MOTOR_FWD, GPIO_PIN_RESET); \
    HAL_GPIO_WritePin(ACTUATOR_PORT_MOTOR_BWD, ACTUATOR_PIN_MOTOR_BWD, GPIO_PIN_SET);   \
} while(0)

#define ACTUATOR_CMD_STOP()  do { \
    HAL_GPIO_WritePin(ACTUATOR_PORT_MOTOR_FWD, ACTUATOR_PIN_MOTOR_FWD, GPIO_PIN_RESET); \
    HAL_GPIO_WritePin(ACTUATOR_PORT_MOTOR_BWD, ACTUATOR_PIN_MOTOR_BWD, GPIO_PIN_RESET); \
} while(0)
